In [6]:
import numpy as np

multi_array_A = np.array([[0,1],[2,3],[4,5]])
#print(multi_array_A)

multi_array_B = np.array([[0,1,2,3],[4,5,6,7]])
#print(multi_array_B)

multi_array_C = np.dot(multi_array_A,multi_array_B) #積の計算
print(multi_array_C)
print(multi_array_C.max()) #要素の最大値

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
